---
name: Build Documentation
on:
  push:
    branches:
      - main

jobs:
  build-docs:
    if: |
      ! contains(github.repository, 'data-science-template') &&
      ! contains(github.event.head_commit.message, 'Initial commit')
    runs-on: [self-hosted, az-ai-runners]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          pip install poetry
          poetry install --only docs

      - run: poetry run mkdocs gh-deploy --force
